### ISSUE TITLE
不思議な空行

### ISSUE THREAD

**Issue by misogihagi** [sakura-cooking/takoyaki#30]
![image](https://github.com/user-attachments/assets/36e177db-dc6b-44df-ad35-cb0cac05aeff)

この段階では〜の前に空行があります。
これはなんのためでしょう？

**Comment by sakagami333** [comment]
![image](https://github.com/user-attachments/assets/17775ea5-6ddc-4bf2-b0db-e475bbf17140)

`<br>` が混入しちゃったみたいです！ ご指摘ありがとうございます。修正します。

#32 #34
