### ISSUE TITLE
だし粉について

### ISSUE THREAD

**Issue by misogihagi** [sakura-cooking/takoyaki#31]
お出汁がついたたこ焼きは好みなのですが、使うだし粉で質問があります。
使っているだし粉は「[ほんだし](https://www.ajinomoto.co.jp/products/detail/?ProductName=hondashi#)」でしょうか？
我が家ではだし粉使ったことがなかったので…

**Comment by sakagami333** [comment]
こんにちわ！質問ありがとうございます。
私たちがおもにつかっているのは一般的に手に入りやすい味の素「ほんだし」をつかっています。
・・・ですが、正直どれでもだいじょうぶです！一番手に入りやすいものを使ってください^^

- https://www.ajinomoto.co.jp/hondashi/

補足ですが、以前 鰹節からとっただしを使って検証したことがあるのですが手間をかけたわりには物足りない結果となりました
