### ISSUE TITLE
えんたこ CB-ETK-1リンク切れ

### ISSUE THREAD

**Issue by yukilab2** [sakura-cooking/takoyaki#33]
CB-ETK-1がリンク切れのようです。 古いHPかもしれませんが、https://www.iwatani-i-collect.com/shop/g/g2000002487/ かもしれません。
ただ、後継機種？が出ているのでimpressionなどもいただけるとありがたいです。
https://www.iwatani.co.jp/jpn/consumer/products/cg/grill/cb-etk-2/ 

レシピありがとうございます。

**Comment by sakagami333** [comment]
ごしてきありがとうございます！
修正いたしました！

#35
